# Page settings

baseURL = "http://lushsleutsky.com/"
languageCode = "en-us"
title = "Lush  Sleutsky | Software Engineer"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
author = "Lush Sleutsky"
description = "An online resume for prospective employers"
primaryColor = "#355e3b"
textPrimaryColor = "#ffffff"

  [params.profile]
  enable = true
  name = "Lush Sleutsky"
  tagline = "Senior Software Engineer"
  avatar = "avatar.png"

  [params.contact]
  enable = true
  location = "Philadelphia, PA"

    [[params.contact.list]]
    icon = "fas fa-phone-square"
    url = "tel:267-307-2019"
    text = "267-307-2019"
    [[params.contact.list]]
    icon = "fas fa-envelope-square"
    url = "mailto:lushsleutsky@gmail.com"
    text = "lushsleutsky@gmail.com"
    # [[params.contact.list]]
    # icon = "fas fa-globe"
    # url = "http://lushsleutsky.com"
    # text = "lushsleutsky.com"

  [params.skills]
  enable = true

    [[params.skills.list]]
    title = "Technical"

      [[params.skills.list.items]]
      details = "JavaScript/TypeScript"
      [[params.skills.list.items]]
      details = "React/Redux/Next.js/Vite"
      [[params.skills.list.items]]
      details = "Node.js/Express/Bun"
      [[params.skills.list.items]]
      details = "Webpack/Babel"
      [[params.skills.list.items]]
      details = "HTML/JSX/Templating"
      [[params.skills.list.items]]
      details = "CSS/SCSS/Sass/LESS"
      [[params.skills.list.items]]
      details = "Tailwind CSS"
      [[params.skills.list.items]]
      details = "CSS-in-JS"
      [[params.skills.list.items]]
      details = "Bootstrap/Material"
      [[params.skills.list.items]]
      details = "AWS/Firebase/DevOps"
      [[params.skills.list.items]]
      details = "Git/CI/CD"
      [[params.skills.list.items]]
      details = "Accessibility/Compliance"

    [[params.skills.list]]
    title = "Professional"

      [[params.skills.list.items]]
      details = "Effective Communication"
      [[params.skills.list.items]]
      details = "Problem Solving"
      [[params.skills.list.items]]
      details = "Analyzation and Collaboration"
      [[params.skills.list.items]]
      details = "Debugging"
      [[params.skills.list.items]]
      details = "Multitasking"
      [[params.skills.list.items]]
      details = "Time management"

  [params.education]
  enable = false

    [[params.education.list]]
    degree = "Computer Science"
    university = "Temple University"
    dates = "2003-2004"
    [[params.education.list]]
    degree = "Computer and Information Sciences"
    university = "Bucks County Community College"
    dates = "2001-2003"

  [params.languages]
  enable = true

    [[params.languages.list]]
    name = "English"
    level = "Native"
    [[params.languages.list]]
    name = "Russian"
    level = "Native"

  [params.interests]
  enable = true

    [[params.interests.list]]
    name = "Technology"
    [[params.interests.list]]
    name = "Artificial Intelligence"
    [[params.interests.list]]
    name = "Contact Sports"
    [[params.interests.list]]
    name = "The Universe"
    [[params.interests.list]]
    name = "Norse Mythology"

  [params.summary]
    enable = true
    text = "I specialize in frontend development - with an emphasis on React - and am driven by a continuous learning ethos. Having spent over a decade honing a pretty laudable skill set has allowed me to produce high-quality deliverables for organizations small and large, as well as enterprise level. I am always looking for new challenges - both professionally and personally - and ever since I built my very first web page dedicated to Michael Jordan back in the mid 90s, my fervor and enthusiasm for technology and engineering has continued to grow exponentially."

  [params.experience]
  enable = true

    [[params.experience.list]]
    title = "Senior Web Engineer"
    dates = "2024 - Present"
    company = "Freelance Developer"
    details = "I have designed a plethora of different user interfaces, responsive design layouts, and SPAs that are geared and optimized for heavy traffic and page views."

      [[params.experience.list.items]]
      details = "Developed various user interfaces using React Router 7, Next.js, Vite, Node.js/Express"
      [[params.experience.list.items]]
      details = "Reducing page load times by 7+ seconds and increasing user retention by upwards of 40%."
      [[params.experience.list.items]]
      details = "Integrated eCommerce functionality into websites, boosting user flows and UX."
      [[params.experience.list.items]]
      details = "Launched successful SEO campaigns that directly affected revenue increases by over 20%."

    [[params.experience.list]]
    title = "Senior Software Developer"
    dates = "2024"
    company = "SLP Toolkit"
    details = "A Next.js web-based service for Speech Language Pathologists, providing tools extending OpenAI and Natural Language Processing for therapists to manage caseloads, create/view students and/or teachers, plan events, and much more."

      [[params.experience.list.items]]
      details = "Built 5 new cutting-edge UI features surrounding retrieving Firestore data via AI assistance."
      [[params.experience.list.items]]
      details = "Enhanced Firebase Cloud Functions to parse user-entered text to return AI-based action."
      [[params.experience.list.items]]
      details = "Incorporated OpenAI and Natural Language Processing functionality into UI features."

    [[params.experience.list]]
    title = "Senior Software Engineer"
    dates = "2023"
    company = "Hovr, Inc"
    details = "A no-code solution that applies a second layer inteface over top an existing website, allowing the addition of anchors, triggers, highlights, and different effects on any element, granularly down to a single letter. This provides content-in-context to an end user's journey, providing anything from videos, images, downloadable content - and more - all without needing to leave the current flow."

      [[params.experience.list.items]]
      details = "Engineered central frontend features with React and Redux Toolkit, built atop the Shdow DOM."
      [[params.experience.list.items]]
      details = "Delivered long-awaited feature-gating functionality, allowing payment tiers for specific features."
      [[params.experience.list.items]]
      details = "Furthered repositories in becoming ADA-compliant, allowing onboarding of major clients."

    [[params.experience.list]]
    title = "Staff Software Engineer"
    dates = "2021-2023"
    company = "ASAP, Inc."
    details = "High-traffic food delivery service primarily targeting the under-served regions of the US, spanning 3 independent sets of web and mobile apps, which would eventually culminate in a Greenfield project combining all essential features from each OpCo into one stylish, modern new website."

      [[params.experience.list.items]]
      details = "Overhauled primary React and Redux codebase, improving developer experience and efficiency."
      [[params.experience.list.items]]
      details = "Instituted performance solutions, elevating raw site speed and boosting fiscal projections."
      [[params.experience.list.items]]
      details = "Led Greenfield project building a new website in Next.js, TypeScrpt, and Tailwind CSS."

    [[params.experience.list]]
    title = "User Interface Developer"
    dates = "2018 - 2021"
    company = "Comcast Business"
    details = "A rapid-iteration, Agile Scrum enterprise environment for building and maintaining Xfinity's internet, voice, and TV options for Business Services Delivery customers."

      [[params.experience.list.items]]
      details = "Merged over 30 modular, reusable components into Storybook frontend workshop."
      [[params.experience.list.items]]
      details = "Boosted test coverage for client-side products to a hard minimum, future-proofing products."

    [[params.experience.list]]
    title = "Full Stack Developer"
    dates = "2017-2018"
    company = "Angus Energy"
    details = "A powerful and fully customizable SaaS logistics and analytics web application for the fuel delivery services sector, consiting of a dashboard with built-to-order widgets with a ton of features."

      [[params.experience.list.items]]
      details = "Migrated Express.js monolith on AngularJS to Angular 6 with Docker, improving scalability."
      [[params.experience.list.items]]
      details = "Captured and converted real-time IoT data from in-field systems, and converted to visual KPIs."

    [[params.experience.list]]
    title = "Solutions Developer"
    dates = "2014-2015"
    company = "Kids Live Safe"
    details = "An online resource providing critical information to the community in regards to child predators, sex offenders, and other threats, surpassing information found on most government-based databases."

      [[params.experience.list.items]]
      details = "Examined, modernized, and optimized legacy frontend code with best practice paradigms."
      [[params.experience.list.items]]
      details = "Conceptualized and wrote adaptive HTML e-mail templates to further marketing campaigns."

    [[params.experience.list]]
    title = "Web Engineer"
    dates = "2012-2017"
    company = "Three Brothers, Inc."
    details = "Modern websites for home services industry that were built based on direct specifications from working with clients from top-to-bottom."

      [[params.experience.list.items]]
      details = "Launched and maintained responsive websites, incorporating jQuery, AngularJS, and Backbone.js"

    [[params.experience.list]]
    title = "Frontend Web Developer"
    dates = "2009 - 2012"
    company = "Shycon Design"
    details = "Wireframing and building eCommerce websites from a diverse set of clients and products, as well as providing SEO and Google AdWords campaigns."

      [[params.experience.list.items]]
      details = "Developed cross-browser compliant websites, minimizing bugs and optimizing data."

  [params.social]
  enable = true

    [[params.social.list]]
    icon = "fab fa-github-square"
    url = "//github.com/lsleutsky"
    title = "GitHub"

      [[params.social.list]]
      icon = "fab fa-linkedin"
      url = "//linkedin.com/in/lushsleutsky"
      title = "LinkedIn"
      [[params.social.list]]
      icon = "fab fa-twitter-square"
      url = "//twitter.com/lsleutsky"
      title = "@LSleutsky"
